function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.12 (R2022a) and Automated Driving Toolbox 3.5 (R2022a).
% Generated on: 14-Jun-2023 12:23:28

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [60.2 20.2 0;
    -20.2 20.2 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [1 1 0], 'Width', 0.2)
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(4, 'Width', 4, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-15.5 18.1 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [-15.5 18.1 0;
    42.9 17.9 0];
speed = [17;17];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
truck = vehicle(scenario, ...
    'ClassID', 2, ...
    'Length', 8.2, ...
    'Width', 2.5, ...
    'Height', 3.5, ...
    'Position', [-4.3 18 0], ...
    'Mesh', driving.scenario.truckMesh, ...
    'Name', 'Truck');
waypoints = [-4.3 18 0;
    57.7 18.2 0];
speed = [15;15];
trajectory(truck, waypoints, speed);

